### ISSUE TITLE
Fix scope of headings to use relevant theme

### ISSUE THREAD

**Issue by remomueller** [remomueller/balance#18]
```scss
@each $name, $theme in $themes {
  @if map-get($theme, menu-bg-scrolled) {
    .theme-#{$name}-bg {
      .navbar-scrolled {
        .menu-#{$name} {
          background-color: map-get($theme, menu-bg-scrolled);
        }
      }
    }
  }
}
```
